name: Notify Cairo Urban News Site to Deploy Documentation
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.CAIRO_URBAN_NEWS_SITE_TOKEN }}
          repository: Project-Cairo-Urban-News/project-cairo-urban-news.github.io
          event-type: update-source